### ISSUE TITLE
Problems with components(?)

### ISSUE THREAD

**Issue by Entity378** [SinsOfSeven/TexFx#12] opened 2024-10-14 14:18 UTC
I don't know why, but in this kokomi skin, the transparency of the components seems completely broken. If you avoid using components and you only use the transparency command then it works correctly (however there is a need to slightly modify the mod)
![Kok_Eldritch_Horror](https://github.com/user-attachments/assets/6a631905-d263-4398-ae56-42cbb3059688)
![Kok_1](https://github.com/user-attachments/assets/173f5fc5-aaf4-4091-8a07-bc01ed1f630b)

**Comment by SinsOfSeven** [comment] 2024-10-26 22:14
Could you please send me an update on this issue after checking it with the latest release?

**Comment by Entity378** [comment] 2024-10-26 22:46
> Could you please send me an update on this issue after checking it with the latest release?

I just checked and the problem remains (I updated both TexFx and ORFix)

**Comment by SinsOfSeven** [comment] 2024-10-28 21:51
I think this issue is related to draw order issues, which texfx was meant to bypass, but could be a real issue still. I will see if I can reproduce the issue, and come up with a fix with doesn't require editing the mod. 

However, I would appreciate a copy of the Mod.ini to confirm this mod does actually use TexFx, since this issue is very common with the old transparency method. You could also include a link to the original source of the mod if you're not sure what to share.

**Comment by Entity378** [comment] 2024-10-30 12:46
> This mod is almost certainly not using TexFx, could you provide me with a link to the original OR upload a copy of the .ini file?
> 
> I think this issue is related to draw order issues, which texfx was meant to bypass because it was a common issue with the older method, but could be a real issue still. I will see if I can reproduce the issue, and come up with a fix with doesn't require editing the mod if it is infact a TexFx issue.

This is the mod in question: https://gamebanana.com/mods/536496
I apologize in advance if it was a problem with kokomi's mod and not with TexFx.
(sorry for the late reply but I haven't been feeling particularly well lately)

**Comment by TerminalAide0017** [comment] 2024-10-30 22:16
This mod does use texfx but they seem to be using it inappropriately, I'll see if it's repairable on the mod side or if the issue needs something else/is not repairable.

**Comment by SinsOfSeven** [comment] 2024-10-31 07:19
This mod was using this "Use Example" from https://github.com/SinsOfSeven/TexFx/blob/85df8b678b352090e0a7d22b2954ba3543832806/hic_sunt_dracones/ComponentFriendlyBuiltinShaders.ini#L3-L15
```ini
; MOD SNIPPET
  if $\texfx\texfx_on
      ib = ResourceKokomiDressIB
      ps-t0 = ResourceKokomiDressDiffuse
      ps-t1 = ResourceKokomiDressLightMap
      ps-t70 = ResourceKokomiDressOutline
      ;ps-t69 = ResourceKokomiTransparencyMap
      $\texfx\_1 = 16770
      $\texfx\_2 = 15360
      run = CommandList\TexFx\SetResourceReferences
      run = CustomShader\TexFx\Component.0
  endif
  drawindexed = 16770, 15360, 0
  run = CommandList\TexFx\ResetResources
  ```

Instead they should use the "Use Example" from [README.md](https://github.com/SinsOfSeven/TexFx/blob/main/README.md) 
```ini
; Use Example
if $Hood == 1
    ps-t0 = ResourceDiffuse
    ps-t1 = ResoourceLightmap
    ps-t69 = ResourceTexFxMask
    $\texfx\glow_intensity = $VAR1
    $\texfx\bloom_intensity = $VAR2
    $\TexFx\_1 = <DRAWINDEX>
    $\TexFx\_2 = <DRAWOFFSET>
    run = CommandList\TexFx\Component.0
endif
```
Which would mean the fix for this mod is this.
```ini
[TextureOverrideKokomiDress]
hash = 74900c81
match_first_index = 52290
ib = ResourceKokomiDressIB
ps-t0 = ResourceKokomiDressDiffuse
ps-t1 = ResourceKokomiDressLightMap
ps-t70 = ResourceKokomiDressOutline

ps-t69 = ResourceKokomiTransparencyMap
$\texfx\_1 = 2586
$\texfx\_2 = 0
run = CommandList\TexFx\Component.0

if $top == 0
      ps-t69 = ResourceKokomiTransparencyMap
      $\texfx\_1 = 16770
      $\texfx\_2 = 15360
      run = CommandList\TexFx\Component.0
      ps-t69 = ResourceKokomiTransparencyMap
      $\texfx\_1 = 7782
      $\texfx\_2 = 2586
      run = CommandList\TexFx\Component.0

else if $top == 1
      ps-t69 = ResourceKokomiTransparencyMap
      $\texfx\_1 = 16770
      $\texfx\_2 = 15360
      run = CommandList\TexFx\Component.0
else if $top == 2
  drawindexed = 2370, 12990, 0
endif
```

Here is the full ini file.
[Kokomi.txt](https://github.com/user-attachments/files/17583336/Kokomi.txt)

**Closed by SinsOfSeven** 2024-10-31 07:19 UTC
